### ISSUE TITLE
Améliorer les prédictions

### ISSUE THREAD

**Issue by LauraGirardet** [CloudyOverhead/acrosome-counter#10]

**Comment by LauraGirardet** [comment]
Un petit exemple imagé de ce qu'il se passe:

Voici des prédictions réaliser sur 5 photos.
![image](https://user-images.githubusercontent.com/81330593/116117809-a8a4c380-a68a-11eb-8699-7fdc1deeeed6.png)

Voici à quoi ressemblait la photo1:
![image](https://user-images.githubusercontent.com/81330593/116118032-eb669b80-a68a-11eb-9025-102ed0e076ce.png)

**Comment by CloudyOverhead** [comment]
Salut! Est-ce que tu peux ajouter la photo en `.tif` pour que je puisse faire des tests? Merci d'avance!

**Comment by CloudyOverhead** [comment]
J'ai publié une nouvelle version qui permet de contrôler le seuil au-delà duquel les prédictions sont filtrées. Comme on manque de données d'entraînement, les scores des prédictions sont vraiment bas. Par contre, par défaut, j'utilisais un seuil de `0.3`, au-dessus duquel il y avait peu de prédictions. J'ai diminué le seuil par défaut à `0.1`. L'effet c'est qu'il y a beaucoup de prédictions mauvaises et des prédictions de spermatozoïdes intacts et intermédiaires qui se superposent. Tu peux faire des tests en ajustant toi-même le seuil (par exemple `python -m acrosome_counter . --infer --review -t 0.2`, pour tester avec un threshold de `0.2`). Dis-moi si ça te convient! 😄
