### ISSUE TITLE
Git pull message d'erreur

### ISSUE THREAD

**Issue by LauraGirardet** [CloudyOverhead/acrosome-counter#12]
Juste au cas ou que ce message d'erreur demande un correctif:

![image](https://user-images.githubusercontent.com/81330593/116634370-d65b6800-a929-11eb-8157-ee1fc2367a5c.png)

**Comment by LauraGirardet** [comment]
je suppose que ca l'est vu le message suivant : 
![image](https://user-images.githubusercontent.com/81330593/116634597-8630d580-a92a-11eb-85a6-9aa0ae3444d3.png)

**Comment by LauraGirardet** [comment]
C'est peut être un soucis sur mon ordi pour la prédiction et pas le tien. SI tu veux toujours essayer la photo 1, puisque les fichiers TIF ne sont pas supportés sur github  je peux t'envoyer cela par email sinon (ou celui ce camille) ?

**Comment by CloudyOverhead** [comment]
Salut! Non, désolé, c'est parce que je travaille sur une branche différente de la dernière fois. Fais `git checkout main` et `git pull`, ça devrait fonctionner! Tu peux m'envoyer des photos jerome@geolearn.ai, si nécessaire. 🙂

**Comment by LauraGirardet** [comment]
Je ne comprends pas trop :
![image](https://user-images.githubusercontent.com/81330593/116741136-ee7fc580-a9c3-11eb-927e-81c405234b3b.png)
![image](https://user-images.githubusercontent.com/81330593/116741160-f8a1c400-a9c3-11eb-89c0-db40536a56d8.png)


Le mail est censuré je vais envoyé à Camille :)

**Comment by LauraGirardet** [comment]
Ca a l'air d'avoir changé de quoi malgré le message d'erreur...
Voici mes prédictions de la facon normal:
![image](https://user-images.githubusercontent.com/81330593/116741943-af05a900-a9c4-11eb-84e2-d267078caac6.png)
et avec le t2:
![image](https://user-images.githubusercontent.com/81330593/116741992-c6449680-a9c4-11eb-9346-4d1494f7c6b1.png)

**Comment by LauraGirardet** [comment]
à noté que mes b ou v sont seulement mes photos en bleu ou en vert ... :/ les deux couleurs sont dans les merges

**Comment by LauraGirardet** [comment]
Les review et changement de treshold fonctionnent donc mais les prédictions sont toujours loins de ce que j'ai dans mes images... j'ai envoyé 3 photo tests sur le ulaval de Camille si vous voulez essayer. :)

**Comment by CloudyOverhead** [comment]
> Le mail est censuré je vais envoyé à Camille :)

Ah, maudit, hahaha! jerome@geolearn.ai

Pour le message d'erreur, essaie de faire `pip install 'git+https://github.com/facebookresearch/detectron2.git'`. Si ça ne marche pas, je vais trouver une autre solution.

Pour les prédictions, en fait, la valeur par défaut est `-t 0.1`. Plus le threshold est bas, plus il y aura de prédictions. Normalement, `--review` devrait te permettre de voir les prédictions pour ajuster le décompte, mais c'est là où il y a une erreur. Je pense que tu n'auras pas le choix de reviewer les photos à ce stade-ci, parce qu'on manque de données d'entraînement. Par exemple, plusieurs détections d'*intermédiaire* se superposent à *perdu* ou *intact*. Par ailleurs, Camille est en train d'annoter d'autres photos pour que les prédictions soient plus fiables.

J'ignore si tu as envoyé des photos non mergées à Camille, mais peux en envoyer une aussi? Ça va me permettre de tester pour le tri des merges. Merci d'avance!

**Comment by CloudyOverhead** [comment]
Est-ce que je me trompe ou est-ce que tes photos sont plus zoomées que celle-ci? (Ou encore tes spermatozoïdes sont-ils plus gros que ceux-ci?)
![image](https://user-images.githubusercontent.com/28260990/116747045-5b4a8e00-a9cb-11eb-95b1-4264e06c1d05.png)

**Comment by CloudyOverhead** [comment]
@LauraGirardet, j'ai mis à jour l'algorithme pour qu'il filtre mieux les photos non mergées. Avertis-moi si jamais tu en retrouves à nouveau dans les prédictions, je vais augmenter le threshold si c'est le cas!

**Comment by LauraGirardet** [comment]
Tu as raison ! J'ai reessayé sur des photos prises de plus loin et ca marche vraiment mieux ! J'avais pas fait attention à cela !!!!
Merci :) c'est assez simple à régler pour moi dans ce cas je dois juste réduire la taille des images zoomées :)


Ok pour la 2eme partie :)

**Comment by CloudyOverhead** [comment]
Je vais inclure des photos plus zoomées au prochain entraînement pour que tu n'aies pas besoin de le faire à la main la prochaine fois! Je peux aussi ajouter tout de suite une option pour changer la taille automatiquement si tu en as beaucoup à traiter. En passant, il faut ajouter une bordure noire aux photos, parce qu'elles sont mise à l'échelle automatiquement par `acrosome-counter`. Par exemple, si tu veux une photo deux fois plus petite, il faut ajouter une bordure noire qui couvre la moitié de la largeur et de la hauteur de la photo finale. Si c'est pas clair, ce serait mieux que je fasse l'opération dans `acrosome-counter`. Laisse-moi savoir! (Si c'est le cas, quel est le zoom sur ta photo et quel est le zoom sur celle que je t'ai montrée, d'après toi?)

**Comment by CloudyOverhead** [comment]
> Pour le message d'erreur, essaie de faire `pip install 'git+https://github.com/facebookresearch/detectron2.git'`. Si ça ne marche pas, je vais trouver une autre solution.

Oh, j'avais pas vu que `--review` marche pour toi! Ignore ce que j'ai dit. :)

**Comment by LauraGirardet** [comment]
Allo, merci beaucoup ! si ce n'est pas compliqué je veux bien une option pour la mise à l'échelle car en effet j'en ai beaucoup dans les deux tailles ! Il y a un rapport de 2,5 entre les deux photos. 
Sinon j'ajouterai en haut et sur les côtés :)

Merci !

**Comment by LauraGirardet** [comment]
Oups un rapport de 2 (pas 2.5)

**Comment by CloudyOverhead** [comment]
Je viens de regarder et c'est facile à implémenter. J'ai besoin de la valeur de zoom (combien de x) pour la photo que je t'ai montrée, est-ce que tu la connais? Dès que je l'ai, je publie une nouvelle version. :)

**Comment by CloudyOverhead** [comment]
D'après Camille, c'est du 20x. Je viens de mettre à jour l'algorithme. Tu peux utiliser l'argument `--zoom 40` pour traiter les photos qui sont plus zoomées (c'est-à-dire `python -m acrosome_counter --infer --review --zoom 40`). Je vais fermer cette issue. N'hésite pas à ouvrir une autre issue si tu trouves un autre problème et à poser des questions si c'est pas clair! Merci de me confirmer si c'est bien 20x et 40x les zooms utilisés. 😄
