### ISSUE TITLE
La commande ne reconnait pas le fichier yaml

### ISSUE THREAD

**Issue by LauraGirardet** [CloudyOverhead/acrosome-counter#3]
![cmd conda](https://user-images.githubusercontent.com/81330593/112380721-1e022a80-8cc0-11eb-8270-fc5901959e4e.PNG)

**Comment by CloudyOverhead** [comment]
Salut, @LauraGirardet! Peux-tu essayer ces [nouvelles instructions](https://github.com/CloudyOverhead/acrosome-counter/tree/fix-release)? S'il y a un problème, envoie-moi l'output. Merci d'avance!

Aussi, peux-tu dire à Camille d'essayer `conda install cython` suivi de `pip install git+https://github.com/DGMaxime/detectron2-windows.git`?

**Comment by LauraGirardet** [comment]
Allo Jérome !

Je ne sais pas si je fais le pip install de la bonne manière car dans tous les cas ce que je fais ne fonctionne pas. Peux tu me dire ce qui n'est pas correct ? Merci de ton aide :)

Laura
![pip install 3](https://user-images.githubusercontent.com/81330593/112384646-0e391500-8cc5-11eb-8440-fa806e001b4c.PNG)
![pip install 2](https://user-images.githubusercontent.com/81330593/112384672-16915000-8cc5-11eb-86e4-c370dc416c10.PNG)

**Comment by camika2** [comment]
![cmd](https://user-images.githubusercontent.com/43100765/112386264-12fec880-8cc7-11eb-807d-516224ce4191.png)
Le premier truc c'était bon mais la partie avec pip install il a vraiment pas aimé ça!

**Comment by CloudyOverhead** [comment]
@LauraGirardet, la première façon était la bonne, mais il y avait une erreur dans le script d'installation. Peux-tu réessayer avec [le nouveau script](https://github.com/CloudyOverhead/acrosome-counter/archive/refs/tags/1.0.zip)?

@camika2, ça a rien changé, mais c'est correct, c'était un tir à l'aveuglette. 😅

**Comment by LauraGirardet** [comment]
![image](https://user-images.githubusercontent.com/81330593/112393375-55c59e00-8cd1-11eb-8b2d-d978f1203cd0.png)
Prise 30291084793

**Comment by CloudyOverhead** [comment]
My bad, désolé. ☹️ Peux-tu réessayer avec [ces nouveaux fichiers](https://github.com/CloudyOverhead/acrosome-counter/archive/refs/heads/fix-release.zip)?

**Comment by LauraGirardet** [comment]
Il faut bien mettre le fichier model_final.pth à quelque part dans le dossier? Dans un dossier appelé logs ou directement dans le dossier unzippé?

**Comment by CloudyOverhead** [comment]
Dans un nouveau dossier appelé `logs` dans celui que tu as unzippé, effectivement! Par contre, ça peut être fait à la toute fin, après que `pip install .` ait réussi à marcher. Est-ce que tu as réussi à installer [CUDA 10.1](https://developer.nvidia.com/cuda-10.1-download-archive-base) et [Visual Studio 2019](https://visualstudio.microsoft.com/fr/downloads/)?

**Comment by LauraGirardet** [comment]
![image](https://user-images.githubusercontent.com/81330593/112394926-dd141100-8cd3-11eb-8f24-3099128de033.png)
Il ne trouve pas le pyproject.toml non plus!

**Comment by LauraGirardet** [comment]
D'accord, c'était déjà fait. Oui pour CUDA et Visual studio c'est fait!

**Comment by LauraGirardet** [comment]
Par contre le setup.py est bien dans le dossier. À quoi sert le point à la fin de la commande?

**Comment by CloudyOverhead** [comment]
> Il ne trouve pas le pyproject.toml non plus!

Il faut peut-être rentrer dans le dossier `acrosome-counter-fix-release/acrosome-counter-fix-release`, s'il y a lieu.

> Par contre le setup.py est bien dans le dossier. À quoi sert le point à la fin de la commande?

Le point sert à dire à `pip` de chercher un `setup.py` dans le dossier actuel.

**Comment by LauraGirardet** [comment]
![image](https://user-images.githubusercontent.com/81330593/112395367-9d015e00-8cd4-11eb-8ec0-3febcbf5cd40.png)

**Comment by LauraGirardet** [comment]
> > Il ne trouve pas le pyproject.toml non plus!
> 
> Il faut peut-être rentrer dans le dossier `acrosome-counter-fix-release/acrosome-counter-fix-release`, s'il y a lieu.

Par contre le fichier pyproject.toml n'est pas là. Il n'est dans aucun des dossiers.

**Comment by CloudyOverhead** [comment]
[Réessaie](https://github.com/CloudyOverhead/acrosome-counter/archive/refs/heads/fix-release.zip), s'il te plaît. L'URL était différent pour ta version de Python, désolé!

> Par contre le fichier pyproject.toml n'est pas là. Il n'est dans aucun des dossiers.

C'est correct, il faut juste l'un ou l'autre. 😃

**Comment by LauraGirardet** [comment]
Ça marchait bien pis après ça marchait pu :( 

![image](https://user-images.githubusercontent.com/81330593/112396531-ae4b6a00-8cd6-11eb-8961-cad52ec41fc9.png)

**Comment by CloudyOverhead** [comment]
Peux-tu essayer `pip install --default-timeout=99999 .`, ou avec un autre chiffre élevé?

**Comment by LauraGirardet** [comment]
![image](https://user-images.githubusercontent.com/81330593/112397503-9674e580-8cd8-11eb-8e00-86190cd6ecd2.png)

Ca reste bloqué là !

**Comment by CloudyOverhead** [comment]
Ça arrive souvent que le terminal de commandes reste bloqué quand on clique dessus. Si tu appuies sur la flèche de gauche, mettons, est-ce que ça débloque?

**Comment by LauraGirardet** [comment]
non ! Je peux fermer la fenetre de commande puis relancer ?

**Comment by CloudyOverhead** [comment]
Oui!

**Comment by LauraGirardet** [comment]
Ca a avancé ! J'en suis là :)
![image](https://user-images.githubusercontent.com/81330593/112399108-00db5500-8cdc-11eb-8cc8-dc451a27b761.png)

**Comment by CloudyOverhead** [comment]
Peux-tu installer [Git](https://git-scm.com/downloads) et réessayer?

**Comment by LauraGirardet** [comment]
Fait ! Mais le même message réapparait

**Comment by CloudyOverhead** [comment]
Il faut peut-être rédémarrer. Peux-tu essayer?

**Comment by LauraGirardet** [comment]
on est comme retourné à un problème précédent il me semble  ^^'
![image](https://user-images.githubusercontent.com/81330593/112401003-f91daf80-8cdf-11eb-8eff-9c0e9e2c5e73.png)

**Comment by CloudyOverhead** [comment]
Peux-tu lancer `conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=10.1 -c pytorch`? Je m'attendais pas à cette erreur-là. Ça peut expliquer pourquoi ça marchait pas sur l'ordi à Camille, merci!

**Comment by CloudyOverhead** [comment]
Et ensuite `pip install git+https://github.com/DGMaxime/detectron2-windows.git`!

**Comment by camika2** [comment]
Je ne me rappelle plus de la version de pytorch qu'il fallait que j'aie. Ce n'est pas la bonne hein? 
![image](https://user-images.githubusercontent.com/43100765/112492232-733d4b00-8d57-11eb-8b1e-2b9783284e7c.png)

**Comment by CloudyOverhead** [comment]
> Je ne me rappelle plus de la version de pytorch qu'il fallait que j'aie. Ce n'est pas la bonne hein?

Je vois même pas `torch` là-dedans, juste `torchvision`, c'est peut-être ça! Fais `conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=10.1 -c pytorch` et `pip install git+https://github.com/DGMaxime/detectron2-windows.git` toi aussi.

**Comment by camika2** [comment]
![image](https://user-images.githubusercontent.com/43100765/112496090-d8df0680-8d5a-11eb-82d2-4975d39001af.png)
![image](https://user-images.githubusercontent.com/43100765/112496258-f7450200-8d5a-11eb-9590-20d58f01375e.png)
![image](https://user-images.githubusercontent.com/43100765/112496438-1e033880-8d5b-11eb-9c28-b0cd0a408d6a.png)

Désolée pour l'ordre des photos, j'ai bien installé les trucs avant, et il me disait que tout était déjà là... La deuxième commande marche pas par contre!

**Comment by LauraGirardet** [comment]
etape 1 ok
![image](https://user-images.githubusercontent.com/81330593/112510855-3c236580-8d68-11eb-8d89-bcb1b01a5f38.png)

etape 2 pas ok avec les mêmes messages d'erreur que Camille

**Comment by CloudyOverhead** [comment]
Pouvez-vous essayer les deux de faire `pip install cython` et `pip install "git+https://github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI"`, et ensuite `pip install git+https://github.com/DGMaxime/detectron2-windows.git`?

**Comment by LauraGirardet** [comment]
![image](https://user-images.githubusercontent.com/81330593/112511853-30846e80-8d69-11eb-8bac-15ffe672b370.png)

etape1 ok
etape2 deux pas ok encore ^^'

**Comment by CloudyOverhead** [comment]
Il manque des guillemets à la commande, je pense. Réessaie en copiant la commande telle quelle. 😃

**Comment by LauraGirardet** [comment]
avec les guillemets ^^
![image](https://user-images.githubusercontent.com/81330593/112512972-434b7300-8d6a-11eb-8e86-15a36edf0650.png)
![image](https://user-images.githubusercontent.com/81330593/112513033-52cabc00-8d6a-11eb-9490-6676c11b0500.png)

**Comment by LauraGirardet** [comment]
je prends les c++ tools vu le message 
![image](https://user-images.githubusercontent.com/81330593/112513658-f1efb380-8d6a-11eb-989a-9fc8096452f2.png)

**Comment by CloudyOverhead** [comment]
Ayoye, parfait, c'est exactement ce que j'allais écrire!

**Comment by CloudyOverhead** [comment]
Camille devrait faire pareil. C'est probablement ça le problème.

**Comment by LauraGirardet** [comment]
Un redémarrage et ca a marché puis _pip install git+https://github.com/DGMaxime/detectron2-windows.git_ également !

**Comment by CloudyOverhead** [comment]
OMG

**Comment by CloudyOverhead** [comment]
Est-ce que `pip install .` fonctionne?

**Comment by LauraGirardet** [comment]
yeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeees

**Comment by LauraGirardet** [comment]
![image](https://user-images.githubusercontent.com/81330593/112521755-4139e200-8d73-11eb-9320-d7ab413a3544.png)

**Comment by CloudyOverhead** [comment]
Ayoye! Tu peux mettre le modèle dans `logs` et essayer de faire la suite des instructions pour essayer d'analyser des photos. Je vais aussi tester avec Camille de mon bord. Je vais fermer cette discussion-ci, mais hésite pas à en repartir une autre s'il y a encore des problèmes! 🚀
