### ISSUE TITLE
Une fois installé - lancement de acrosome counter

### ISSUE THREAD

**Issue by LauraGirardet** [CloudyOverhead/acrosome-counter#4]
Allo, 

Je n'arrive pas à lancer le pgm sur mes échantillons. Je fais qlq chose de pas correct n'est-ce pas ?

Puis autre question, mes fichiers doivent-ils être nommés d'une certaine façon?

Merci :) 

![image](https://user-images.githubusercontent.com/81330593/114239492-290db980-9954-11eb-86e4-9e8121c10037.png)

**Comment by CloudyOverhead** [comment]
Salut!

Non, tu sembles avoir fait la bonne chose. Peux-tu lancer `pip list` et me montrer l'output?

Tu n'as pas besoin de nommer tes fichiers d'une façon particulière et `acrosome-counter` analyse tous les sous-dossiers pour trouver tes photos. Par exemple, tu pourrais lancer la commande dans `excel spz` juste une fois et tous tes dossiers seraient traités. 😄

**Comment by LauraGirardet** [comment]
Pip list dans acrosom counter ? 
![image](https://user-images.githubusercontent.com/81330593/114250549-10a99900-996c-11eb-9918-4ec01dc6ec17.png)
![image](https://user-images.githubusercontent.com/81330593/114250574-25862c80-996c-11eb-9c04-53f07518e163.png)
![image](https://user-images.githubusercontent.com/81330593/114250596-33d44880-996c-11eb-9957-b68051aa0f0f.png)
![image](https://user-images.githubusercontent.com/81330593/114250607-464e8200-996c-11eb-9679-4ceed8b32014.png)
![image](https://user-images.githubusercontent.com/81330593/114250626-55cdcb00-996c-11eb-9e4c-4ce469078b7b.png)
![image](https://user-images.githubusercontent.com/81330593/114250640-61b98d00-996c-11eb-9337-8d549669cc35.png)

**Comment by LauraGirardet** [comment]
TOP ! Puis sais tu si j'ai des photos avec seulement le bleu ou seulement le vert ca ne va pas en tenir et compte et prendre les photos seulement si ce sont des merges (2 couleurs) ?

**Comment by LauraGirardet** [comment]
C'est le pyobc à priori le problème

**Comment by CloudyOverhead** [comment]
> Pip list dans acrosom counter ?

N'importe où, mais je vois que `acrosome-counter` est dans la liste, c'est étrange que ça marche pas. Peux-tu me montrer l'output des commandes `where python` et `pip show acrosome-counter`? Peux-tu me montrer le contenu du dossier vers lequel pointe l'output de `pip show acrosome-counter`?

**Comment by CloudyOverhead** [comment]
> TOP ! Puis sais tu si j'ai des photos avec seulement le bleu ou seulement le vert ca ne va pas en tenir et compte et prendre les photos seulement si ce sont des merges (2 couleurs) ?

Je n'y avais pas pensé! C'est facile à vérifier, je vais l'implémenter quand on aura réglé ce problème.

**Comment by LauraGirardet** [comment]
Allo !
Voici les infos :)
![image](https://user-images.githubusercontent.com/81330593/114419602-8f2b5400-9b81-11eb-9ef5-0ae31a8626c2.png)
![image](https://user-images.githubusercontent.com/81330593/114419975-e6312900-9b81-11eb-9bff-87dbcada8524.png)
![image](https://user-images.githubusercontent.com/81330593/114420033-f3e6ae80-9b81-11eb-9868-8939e0dc1cb8.png)
![image](https://user-images.githubusercontent.com/81330593/114420098-052fbb00-9b82-11eb-97b8-7ad7aa567aa0.png)
![image](https://user-images.githubusercontent.com/81330593/114420195-1e386c00-9b82-11eb-8c07-2b23dbdfbfcb.png)
![image](https://user-images.githubusercontent.com/81330593/114420257-28f30100-9b82-11eb-9312-438db6b5030f.png)

**Comment by CloudyOverhead** [comment]
Si tu fais `pip install -e .` plutôt que `pip install .`, est-ce qu'il y a un dossier `acrosome_counter` (sans `-1.0.dist-info`) qui apparaît dans `C:\Users\Laura\Anaconda3\Lib\site-packages`? Si oui, réessaie de lancer le programme. Sinon, fais-moi juste savoir, je pense que je sais quel est le problème.

**Comment by LauraGirardet** [comment]
Je ne sais pas ce que j'ai fais mais j'ai changé la localisation de acrosome counter en faisant pip install -e. dans son  dossier 
![image](https://user-images.githubusercontent.com/81330593/114591887-57dba680-9c58-11eb-96cb-56bb5da02ef6.png)

Je n'ai pas d'acrosome-counter qui apparait dans _C:\Users\Laura\Anaconda3\Lib\site-package_

**Comment by CloudyOverhead** [comment]
Ok, merci! Tu peux [retélécharger `acrosome-counter`](https://github.com/CloudyOverhead/acrosome-counter/releases/tag/1.0) et réessayer. Tiens-moi au courant!

**Comment by LauraGirardet** [comment]
Alors je l'ai téléchargé, extrait, puis fais pip install -e .  etait-ce bien la marche à suivre ? Voici le résultat:

![image](https://user-images.githubusercontent.com/81330593/114747527-ed416e00-9d1e-11eb-8806-0c3f2d8680fa.png)

**Comment by CloudyOverhead** [comment]
Désolé, GitHub a fait quelque chose de bizarre quand j'ai packagé le projet. Tu peux réessayer de downloader!

**Comment by LauraGirardet** [comment]
Je ne vois pas de différences je pense comparé à avant ... 

![image](https://user-images.githubusercontent.com/81330593/115067843-7394b600-9ebf-11eb-9fd9-0ae5a2153949.png)

**Comment by LauraGirardet** [comment]
![image](https://user-images.githubusercontent.com/81330593/115067998-a63eae80-9ebf-11eb-87ef-0a5beabb94bc.png)

**Comment by CloudyOverhead** [comment]
Réessaie sans les accents (\`\`). C'est juste pour formatter le code dans GitHub, ça devrait pas se retrouver dans les commandes, désolé!

**Comment by LauraGirardet** [comment]
Ok le message change en effet ! Pas certaine que ca a marché par contre, le fichier excel devrait se mettre ou?

![image](https://user-images.githubusercontent.com/81330593/115068676-8fe52280-9ec0-11eb-9923-f35e6d391d8c.png)

**Comment by CloudyOverhead** [comment]
> Pas certaine que ca a marché par contre, le fichier excel devrait se mettre ou?

Directement dans le dossier où tu as lancé la commande. 🙂 C'est cool, ça progresse, maintenant ton ordi détecte le package.

Je déduis de ce que je vois que la version de Detectron2 comporte des différences mineures. J'ai ajouté une correction. Tu peux retélécharger le package. Désolé pour les manipulations répétitives. 😞

**Comment by LauraGirardet** [comment]
![image](https://user-images.githubusercontent.com/81330593/115098233-e5d7bb80-9efc-11eb-92d2-df89cfb16826.png)

toujours le même problème ! (pas de pb pour les manips répétitives ca avance en effet :) )

**Comment by CloudyOverhead** [comment]
On aurait dû faire ceci pour que tu aies moins de manips à faire à chaque essai:
- Lance la commande `git clone -b  fix-release https://github.com/CloudyOverhead/acrosome-counter.git` dans le dossier où tu télécharges `acrosome-counter` habituellement.
- Lance la commande `git pull` dans le dossier `acrosome-counter` quand j'apporte des modifications.

J'ai corrigé le nouveau bug, tu peux réessayer la procédure. :) Tu n'as pas à lancer `git pull` pour cette fois-ci.

**Comment by LauraGirardet** [comment]
Oups je suis perdue ...
Voici ce que j'ai fait:
![image](https://user-images.githubusercontent.com/81330593/115790542-de992d80-a394-11eb-9bdb-6ce5aa5f04b1.png)

![image](https://user-images.githubusercontent.com/81330593/115790630-04263700-a395-11eb-926a-37edac8008bc.png)

![image](https://user-images.githubusercontent.com/81330593/115790842-5e26fc80-a395-11eb-94de-a376bdcf4352.png)

J'ai essayé git pull juste au cas ou car ca ne marchait pas...

J'ai manqué quelque chose ?

**Comment by CloudyOverhead** [comment]
Ok, je vais être plus spécifique!
- Retire de `C:\Users\laura\Downloads\` toutes les versions d'`acrosome-counter` que tu aies pu downloader.
- Lance `git clone -b fix-release https://github.com/CloudyOverhead/acrosome-counter.git` dans `C:\Users\laura\Downloads\`
- Va dans `C:\Users\laura\Downloads\acrosome-counter-1.0`
- Lance `pip install -e .`
Si j'apporte d'autres modifications, tu auras seulement à lancer `git pull` dans `C:\Users\laura\Downloads\acrosome-counter-1.0` et tu n'auras **pas** besoin de lancer `pip install -e .` à nouveau (ni retélécharger quoi que ce soit).

J'espère que c'est plus clair! Tiens-moi au courant. 😄

**Comment by LauraGirardet** [comment]
ahah merci c'est plus clair, merci :)

Voici après avoir supprimé le reste
![image](https://user-images.githubusercontent.com/81330593/115798739-f082cc80-a3a4-11eb-9e2b-582c48c9b99d.png)

**Comment by LauraGirardet** [comment]
Vu le message j'ai retéléchargé le model_final et fais un nouveau dossier logs

Je l'ai essayé ici
![image](https://user-images.githubusercontent.com/81330593/115799254-0e9cfc80-a3a6-11eb-8d24-66bbaca1064a.png)
et ici, mais pas de différences
![image](https://user-images.githubusercontent.com/81330593/115799287-207e9f80-a3a6-11eb-912c-009d73bd7869.png)

peux-tu me redire ou je dois le mettre ?

**Comment by CloudyOverhead** [comment]
Bonne initiative! C'est le dossier `logs` que tu as placé à ces endroits? Si oui, j'ai introduit un bug, désolé. Essaie de placer le dossier `logs` dans le dossier duquel tu lances `python acrosome-counter ...` et dis-moi ce qui se produit. 🙂

**Comment by LauraGirardet** [comment]
Oui c'était le log que je mettais là !
Voilà quand je le place dans mon dossier ou je veux lancer l'analyse : 
![image](https://user-images.githubusercontent.com/81330593/115822822-2dfe4e80-a3d3-11eb-9252-3f33af583604.png)

**Comment by CloudyOverhead** [comment]
Ok, c'est corrigé! Lance `git pull`  dans `C:\Users\laura\Downloads\acrosome-counter-1.0` et réessaie. Désolé de l'inconvénient!

**Comment by LauraGirardet** [comment]
Ok ca fonctionne !!!!!!!!!! :) 💯 👍 

J'ai en effet mis le dossier logs dans ce que je veux étudier, puis c'est bon !

Doooonc je suis maintenant avec un fichier prédiction excel par contre les prédictions sont fuckées je ne sais pas trop pourquoi... j'ai essayé de retravailler des images pour que le phénotype soit hyper clair mais c'est toujours pas ca :/ 

On peut passer sur une autre 'issue' pour essayer de voir cela peut-être :)

**Comment by CloudyOverhead** [comment]
Yay! :)

Effectivement, pars une autre issue pour ça. Ajoute des photos, je vais pouvoir diagnostiquer ça. C'est sûrement juste parce que les photos sont un peu différentes de celles sur lesquelles l'algorithme s'est entraîné.

Je vais intégrer les modifications dont on s'est parlés (#5 et #6).

**Comment by CloudyOverhead** [comment]
> Je vais intégrer les modifications dont on s'est parlés (#5 et #6).

@LauraGirardet, c'est fait! Tu peux retélécharger le projet. Tu n'auras qu'à laisser `logs` dans `acrosome-counter` et les fichiers non mergés vont être ignorés automatiquement.

**Comment by LauraGirardet** [comment]
Allo ! Voici ce que cela donne quand ca ne s'ouvre pas:


(base) C:\Users\laura\Desktop\bovins 24-03-21\t1\ca\avant>python -m acrosome_counter . --infer --review
Traceback (most recent call last):
  File "C:\Users\laura\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\laura\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\users\laura\downloads\acrosome-counter\acrosome_counter\__main__.py", line 56, in <module>
    main(args)
  File "c:\users\laura\downloads\acrosome-counter\acrosome_counter\__main__.py", line 40, in main
    dataset.review()
  File "c:\users\laura\downloads\acrosome-counter\acrosome_counter\load_dataset.py", line 168, in review
    visualize(image, instances, self.metadata)
  File "c:\users\laura\downloads\acrosome-counter\acrosome_counter\visualize.py", line 31, in visualize
    out = visualizer.draw_instance_predictions(instances)
  File "C:\Users\laura\anaconda3\lib\site-packages\detectron2\utils\visualizer.py", line 387, in draw_instance_predictions
    classes = predictions.pred_classes.tolist() if predictions.has("pred_classes") else None
AttributeError: 'list' object has no attribute 'tolist'

**Comment by CloudyOverhead** [comment]
Salut! Remplace `acrosome-counter/acrosome_counter/load_dataset.py` par [ce fichier](https://github.com/CloudyOverhead/acrosome-counter/blob/fix-review/acrosome_counter/load_dataset.py).

**Comment by CloudyOverhead** [comment]
Avertis-moi si ça fonctionne. 😃

**Comment by LauraGirardet** [comment]
ca fonctionne !
